### ISSUE TITLE
CORRECTION FOR NICKSON

### ISSUE THREAD

**Issue by freddykurniawan** [stevenwalentino/heroes-website#7]
Please fix the following:
1. Navbar active tab: please fix the navbar for pm, ss, and cg. If you look at them now, they are not consistent.
2. Why pm, ss, and cg all have the same cover pics? Also please resize the cover pic in pm, ss, and cg to be the standard cover pic in other pages
3. Standardize all page name into "Heroes & Legends"

**Comment by nicksonjulian** [comment]
fixed.
